services:
  postgres:
    image: postgres:16-alpine
    container_name: stockmaster-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: stockmaster_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data

  postgres_test:
    image: postgres:16-alpine
    container_name: stockmaster_postgres_test
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_USER: usuario_teste
      POSTGRES_PASSWORD: senha_teste
      POSTGRES_DB: stockmaster_test

  api:
    build: .
    container_name: stockmaster-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PORT: 3000
      DATABASE_URL: "postgresql://postgres:postgrespassword@postgres:5432/stockmaster_db?schema=public"
      JWT_SECRET: "uma_chave_super_segura"
    command: sh -c "npx prisma db push && npm run dev"
    depends_on:
      - postgres

volumes:
  postgres_data:
